#!/usr/bin/env bash

set -Eeuo pipefail

readonly WD="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

main() {
  [[ -n "${DEBUG:-}" ]] && set -x;

  local debian_version='buster'

  while getopts ':j' opt; do
    case "${opt}" in
      j) debian_version='jessie';;
      *) ;;
    esac
  done
  shift "$((OPTIND-1))"

  local -r ruby_version="${1:-}"
  local -r version="$(git -C "${WD}" describe --tags --abbrev=0 | sed 's/^v//')"
  echo -n "ruby-${ruby_version}:${version}-${debian_version}"
}

main "$@"
